### ISSUE TITLE
需要补充文档

### ISSUE THREAD

**Issue by hackstoic** [crawlab-team/artipub#1]
首先，这是一个很棒的工具 。当看到这个工具的时候，觉得很惊喜，因为这是我一直以来要寻找的工具。 之前确实遇到这类痛点。发布多平台时，需要一个个登录，复制粘贴。 虽然网络上有一些新媒体多平台工具，但是更多是针对头条，百度百家，网易号等通用自媒体平台，针对技术类网站的比较少。 

这个项目文档比较少，希望作者能够补充文档，让我们尽快玩起来，感恩！

**Comment by tikazyq** [comment]
现在可以玩起来了，请查看README
