### ISSUE TITLE
如果使用 rod 就可以和 crawlab 技术栈统一了

### ISSUE THREAD

**Issue by ysmood** [crawlab-team/artipub#104]
项目地址：https://github.com/go-rod

可以看这个例子 https://github.com/go-rod/v2ex-example

crawlab 主项目用的 golang，这个项目完全可以只用 golang 完成全部功能，而且不需要用户额外安装 chrome 插件。和 puppeteer 的对比可以见我们的 readme。

~~老哥去了我 v2ex 的帖子里打广告，我也来回敬一下😄~~

**Comment by tikazyq** [comment]
发错了，这是artipub的项目，请发在crawlab里
