### ISSUE TITLE
最近重新安装失败，axios相关模块报错了

### ISSUE THREAD

**Issue by CharMingF** [crawlab-team/artipub#111]
之前安装成功可用了，最近重新安装，看到有更新，但是安装失败了。

app_1    |
app_1    | > backend@1.0.0 start:backend /app
app_1    | > node server.js
app_1    |
app_1    | module.js:550
app_1    |     throw err;
app_1    |     ^
app_1    |
app_1    | Error: Cannot find module 'axios'
app_1    |     at Function.Module._resolveFilename (module.js:548:15)
app_1    |     at Function.Module._load (module.js:475:25)
app_1    |     at Module.require (module.js:597:17)
app_1    |     at require (internal/module.js:11:18)
app_1    |     at Object.<anonymous> (/app/spiders/base.js:8:15)
app_1    |     at Module._compile (module.js:653:30)
app_1    |     at Object.Module._extensions..js (module.js:664:10)
app_1    |     at Module.load (module.js:566:32)
app_1    |     at tryModuleLoad (module.js:506:12)
app_1    |     at Function.Module._load (module.js:498:3)
app_1    |     at Module.require (module.js:597:17)
app_1    |     at require (internal/module.js:11:18)
app_1    |     at Object.<anonymous> (/app/spiders/juejin.js:1:82)
app_1    |     at Module._compile (module.js:653:30)
app_1    |     at Object.Module._extensions..js (module.js:664:10)
app_1    |     at Module.load (module.js:566:32)
app_1    | npm ERR! code ELIFECYCLE
app_1    | npm ERR! errno 1
app_1    | npm ERR! backend@1.0.0 start:backend: `node server.js`
app_1    | npm ERR! Exit status 1
app_1    | npm ERR!
app_1    | npm ERR! Failed at the backend@1.0.0 start:backend script.
app_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1    |
app_1    | npm ERR! A complete log of this run can be found in:
app_1    | npm ERR!     /root/.npm/_logs/2020-10-09T08_49_38_350Z-debug.log
artipub_app_1 exited with code 1

**Comment by fanshengliang** [comment]
遇到同样的问题，无论docker安装、npm安装，还是源码安装都跑不起来。

**Comment by iefc** [comment]
遇到同样的问题，有解决方案吗

**Comment by CharMingF** [comment]
> 遇到同样的问题，有解决方案吗



> 遇到同样的问题，无论docker安装、npm安装，还是源码安装都跑不起来。
docker放弃了，源码安装后会报错，但是不影响使用。

**Comment by fanshengliang** [comment]
@CharMingF @dogfei 

docker、npm、源码三种方式我都试过了，都不行，我找到变通解决方案了。
应该是作者更新了代码，而更新后的代码有问题，而作者同时更新了dockerhub上docker镜像，而docker镜像里面的代码也是更新后的，所以根本跑不起来。

解决方案是，有人下载过之前的docker镜像，并且改了个名字push到了dockerhub。
地址：https://hub.docker.com/r/gogobody/artipush。
pull这个docker镜像，修改yaml文件跑这个镜像就可以了。

程序能够起来，并且测试过“SegmentFault”与“开源中国”能够正常发布，“简书”、“知乎”、“微信公众号”没有试过，“CSDN”、“V2ex”、“掘金”、“博客园”发布会错误。

**Comment by luwanglin** [comment]
我也遇到了同样的问题

**Comment by FLVE** [comment]
同样的问题，现在有解决的方法没有？
