### ISSUE TITLE
docker-compose安装(node:34) UnhandledPromiseRejectionWarning: ReferenceError: d is not defined错误说明

### ISSUE THREAD

**Issue by ncs19960831** [crawlab-team/artipub#130]
问题介绍：
       使用Debian10 docker-compose安装，服务启动之后，当前端口8000可以正常查看到界面。但是没有任何的cookie显示，而使用调试界面提示错误的调用。

访问 http://localhost:3000/platforms/checkCookies时无响应
![image](https://user-images.githubusercontent.com/17774506/104083399-2b8b4500-5279-11eb-9aa7-a27372b5b324.png)
进入docker的log输出，可以看到有报错，错误的位置似乎是某个函数的参数未定义。

详细查看到，代码的更新记录似乎是直接添加在内。因为我对java相关的代码并不熟悉，所以只能在此写下大概的错误，具体的需要各位开发人员进行查看
![image](https://user-images.githubusercontent.com/17774506/104083431-68efd280-5279-11eb-8692-29c893eed1a2.png)

**如有需要的帮助，请在下方回复**

**Comment by acooler15** [comment]
`platforms/checkCookies`是post请求，get访问会出错。

若运行在本地，可用浏览器访问[http://localhost:3000/platforms](http://localhost:3000/platforms)来验证后端是否正常启动。

**Comment by ncs19960831** [comment]
访问过，返回的数据是正常的，看起来是各个博客的数据。但是在前端界面似乎无法显示

**Comment by ncs19960831** [comment]
{"status":"ok","data":[{"_id":"5ff8647171951500286ad3b5","name":"juejin","label":"掘金","editorType":"markdown","url":"https://juejin.cn","description":"掘金是一个帮助开发者成长的社区，是给开发者用的 Hacker News，给设计师用的 Designer News，和给产品经理用的 Medium。掘金的技术文章由稀土上聚集的技术大牛和极客共同编辑为你筛选出最优质的干货，其中包括：Android、iOS、前端、后端等方面的内容。用户每天都可以在这里找到技术世界的头条内容。与此同时，掘金内还有沸点、掘金翻译计划、线下活动、专栏文章等内容。即使你是 GitHub、StackOverflow、开源中国的用户，我们相信你也可以在这里有所收获。","enableImport":false,"enableLogin":true,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3b6","name":"segmentfault","label":"SegmentFault","editorType":"markdown","url":"https://segmentfault.com","description":"SegmentFault 思否 为开发者提供问答、学习与交流编程知识的平台，创造属于开发者的时代！","enableImport":false,"enableLogin":true,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3b7","name":"csdn","label":"CSDN","editorType":"rich-text","url":"https://blog.csdn.net","description":"CSDN博客-专业IT技术发表平台","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"exists"},{"_id":"5ff8647171951500286ad3b8","name":"jianshu","label":"简书","editorType":"markdown","url":"https://jianshu.com","description":"简书是一个优质的创作社区，在这里，你可以任性地创作，一篇短文、一张照片、一首诗、一幅画……我们相信，每个人都是生活中的艺术家，有着无穷的创造力。","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3b9","name":"zhihu","label":"知乎","editorType":"markdown","url":"https://zhihu.com","description":"有问题，上知乎。知乎，可信赖的问答社区，以让每个人高效获得可信赖的解答为使命。知乎凭借认真、专业和友善的社区氛围，结构化、易获得的优质内容，基于问答的内容生产方式和独特的社区机制，吸引、聚集了各行各业中大量的亲历者、内行人、领域专家、领域爱好者，将高质量的内容透过人的节点来成规模地生产和分享。用户通过问答等交流方式建立信任和连接，打造和提升个人影响力，并发现、获得新机会。","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"exists"},{"_id":"5ff8647171951500286ad3ba","name":"oschina","label":"开源中国","editorType":"rich-text","url":"https://oschina.net","description":"OSCHINA.NET 是目前领先的中文开源技术社区。我们传播开源的理念，推广开源项目，为 IT 开发者提供了一个发现、使用、并交流开源技术的平台","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3bb","name":"toutiao","label":"今日头条","editorType":"markdown","url":"https://toutiao.com","description":"《今日头条》(www.toutiao.com)是一款基于数据挖掘的推荐引擎产品，它为用户推荐有价值的、个性化的信息，提供连接人与信息的新型服务，是国内移动互联网领域成长最快的产品服务之一。","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3bc","name":"cnblogs","label":"博客园","editorType":"rich-text","url":"https://cnblogs.com","description":"博客园是一个面向开发者的知识分享社区。自创建以来，博客园一直致力并专注于为开发者打造一个纯净的技术交流社区，推动并帮助开发者通过互联网分享知识，从而让更多开发者从中受益。博客园的使命是帮助开发者用代码改变世界。","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3bd","name":"v2ex","label":"V2ex","editorType":"markdown","url":"https://v2ex.com","description":"v2ex，是一个汇集各类奇妙好玩的话题和流行动向的网站。V2EX 提供了特别有用的小工具 [ ZEN ]，帮助你掌握自己的时间。V2EX 中充满了各种各样精心雕琢的细节。","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3be","name":"wechat","label":"微信公众号","editorType":"rich-text","url":"https://mp.weixin.qq.com","description":"微信公众平台,微信公众平台官方网站,公众号注册,微信公众号注册,微信订阅号注册,微信公众号申请,微信服务号申请,微信订阅号申请,微信企业号申请,微信服务号注册,微信企业号注册,订阅号注册,公众号申请,服务号申请,订阅号申请,企业号申请,服务号注册,企业号注册,微信","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"},{"_id":"5ff8647171951500286ad3bf","name":"aliyun","label":"阿里云开发者社区","editorType":"markdown","url":"https://developer.aliyun.com/","description":"阿里云开发者社区集合阿里巴巴经济体各个单元技术优势，提供分享、交流、学习、认证、工具、资源、大赛、活动、社群、MVP、创新中心等一站式服务能力，满足开发者全生命周期成长需求。","enableImport":false,"enableLogin":false,"__v":0,"cookieStatus":"no_cookie"}]}
这些就是返回的数据

**Comment by acooler15** [comment]
问题可能在`URL Scheme must be 'http' or 'https' for CORS request`这里了，访问[http://localhost:8000/umi.99ffe39e.js](http://localhost:8000/umi.99ffe39e.js)，搜索'localhost:3000'，看下f的值。方便的话，贴下你的docker-compose.yml

**Comment by ncs19960831** [comment]
感谢您给我的建议，这个问题似乎是因为我的内部代理出现的问题，这个问题也已经被我解决了。但还有另一个类似的问题，下面会另开一个issue
