### ISSUE TITLE
ARTIPUB_API_ADDRESS宏无法覆盖对于后端的访问

### ISSUE THREAD

**Issue by ncs19960831** [crawlab-team/artipub#131]
这个是我的配置环境：
服务器端：Debian10 docker-compose搭建。
客户端：Chrome。
两者使用两个虚拟机进行搭建，现在可以确认的是两者是可以联通的。
而当前的宿主机已经可以访问8000的前端界面，但是后端的访问还是有问题。
docker-compose.yaml文件如下：
```shell
version: '3.3'
services:
  app:
    image: "tikazyq/artipub:latest"
    environment:
      MONGO_HOST: "mongo"
      ARTIPUB_API_ADDRESS: "192.168.116.129:3000" # 后端API地址，如果安装地址不在本机，请修改为服务器IP地址+端口号（默认为3000）
    ports:
      - "8000:8000" # frontend
      - "3000:3000" # backend
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

```
虽然使用了ARTIPUB_API_ADDRESS重定义，但实际上在客户端上对于platform的请求还是使用了**localhost**这个地址。

![image](https://user-images.githubusercontent.com/17774506/104088929-5b504200-52a5-11eb-8c76-f2e15408af8f.png)

我不清楚还可以做什么解决这个问题。而我使用artipub助手可以确认直接使用**ARTIPUB_API_ADDRESS**的地址是可以连接后端的。

也就是说，主要的问题应该还是在这个localhost的映射无法准确的被替换。可否能给我一些帮助呢？

**Comment by acooler15** [comment]
可能是浏览器缓存问题，强制刷新，或者清理缓存试试

**Comment by ncs19960831** [comment]
清除了之后似乎出现了新的情况。
![image](https://user-images.githubusercontent.com/17774506/104090369-44175180-52b1-11eb-9136-0178c32b2e74.png)
出现了如上图的错误的请求。
经过简单的查看源代码，我找到了可能的异常位置：extensions\src\popup\Popup.tsx line29.
我还不清楚是否是这里是具体的问题。但我现在也只能做到这里了。

**Comment by ncs19960831** [comment]
我尝试注释掉了ARTIPUB_API_ADDRESS这个宏定义，只采用服务器端的前端，可以正常使用。
所以这个问题似乎是在做宏定义替换的时候出现的问题。
也就是可能的故障点还可能是**docker_init.sh**文件内的宏定义替换出现的情况。

**Comment by acooler15** [comment]
将`192.168.116.129:3000`改为`http://192.168.116.129:3000`

**Comment by ncs19960831** [comment]
感谢，确实替换为http即可。
