### ISSUE TITLE
windows chrome拓展报错

### ISSUE THREAD

**Issue by AllentDan** [crawlab-team/artipub#141]
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined

popup.js:36051 (匿名函数)

**Comment by acooler15** [comment]
看下后端地址有没有配置正确，再重新点击试一下。

**Comment by AllentDan** [comment]
是从源码安装的
后端port是3000。在后端启动运行npm run start时产生如下错误
20 error code ELIFECYCLE
21 error errno 1
22 error artipub-backend@0.1.6 start: `node server.js`
22 error Exit status 1
23 error Failed at the artipub-backend@0.1.6 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
是因为没有编译正确吗

**Comment by tanliyuan** [comment]
后端启动日志有报什么错吗，0.1.6后端还是js，不需要编译
