### ISSUE TITLE
登陆助手下载 404 报错

### ISSUE THREAD

**Issue by Smith-Cruise** [crawlab-team/artipub#145]
安装方式是 docker-compose 一键安装的方式，安装完成后在里面下载登陆助手，一直报错 404，下载不了。
请求的地址是：http://localhost:8000/artipub-helper.zip#/helper
chrome 是 89 版本的。

**Comment by tanliyuan** [comment]
暂时先从 https://github.com/crawlab-team/artipub/releases/tag/v0.1.5 (或者 https://gitee.com/tanliyuan/artipub/releases/v0.1.5 ）  
 这里下载吧，原来打包后的插件放到源码里面的，导致源码过大影响clone,被我移除了，后面从 release 里面下载，后面我修复下下载连接
