### ISSUE TITLE
http://localhost:8000/artipub-helper.zip 登录助手404

### ISSUE THREAD

**Issue by wt1024** [crawlab-team/artipub#146]
http://localhost:8000/artipub-helper.zip 登录助手404
请问下是我哪里设置的不对么？

**Comment by tanliyuan** [comment]
拉取最新代码已经修复，或者 https://gitee.com/tanliyuan/artipub/releases/v0.1.5 这里下载

**Comment by wt1024** [comment]
> 拉取最新代码已经修复，或者 https://gitee.com/tanliyuan/artipub/releases/v0.1.5 这里下载

感谢回复，辛苦了，多谢
