### ISSUE TITLE
请教一下，如果写的图床地址，artipub会分别上传到各平台的图片吗？ 还是各平台都用图床地址？

### ISSUE THREAD

**Issue by chenbihao** [crawlab-team/artipub#154]
请教一下，如果写的图床地址，artipub会分别上传到各平台的图片吗？ 还是各平台都用图床地址？

**Comment by chenbihao** [comment]
有点困惑，因为自己图床速度很慢，如果各平台都用自己图床地址的话感觉体验可能不太好，所以想问问系统的机制是帮忙把图片上传到各平台，还是直接贴上图床地址？

**Comment by acooler15** [comment]
图片上传功能现在还没有实现。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crawlab-team/artipub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [crawlab-team/artipub] 请教一下，如果写的图床地址，artipub会分别上传到各平台的图片吗？ 还是各平台都用图床地址？ (#154)





 
有点困惑，因为自己图床速度很慢，如果各平台都用自己图床地址的话感觉体验可能不太好，所以想问问系统的机制是帮忙把图片上传到各平台，还是直接贴上图床地址？

**Comment by chenbihao** [comment]
意思是目前只支持文本吗，图片上传有计划实现吗

**Comment by acooler15** [comment]
> 意思是目前只支持文本吗，图片上传有计划实现吗

现在只能自己先上传图床，再粘贴链接。图片上传功能以后会解决。

**Comment by tanliyuan** [comment]
> 有点困惑，因为自己图床速度很慢，如果各平台都用自己图床地址的话感觉体验可能不太好，所以想问问系统的机制是帮忙把图片上传到各平台，还是直接贴上图床地址？

- 有的平台在发布文章时，如果监测到外链图片url，会自动上传到平台自身cdn，然后替换图片地址，如掘金；

- 有的平台是保留外链图片url；

- 还有的平台是文章中不允许出现外链图片url，要手动在平台上传图片，如今日头条。
