### ISSUE TITLE
master 打包docker镜像的时候报错

### ISSUE THREAD

**Issue by silently9527** [crawlab-team/artipub#159]
![image](https://user-images.githubusercontent.com/5729336/114420731-25de2c00-9be7-11eb-9bff-eea91ee7c107.png)

**Comment by tanliyuan** [comment]
发下打包命令

**Comment by silently9527** [comment]
在工程目录下：

docker build -t xxx/artipub:v1 .

**Comment by acooler15** [comment]
稍等，已找到问题
jelastic/nodejs:14.16.0-npm默认使用了npm@7
