### ISSUE TITLE
npm install安装好慢

### ISSUE THREAD

**Issue by AndrewAndrea** [crawlab-team/artipub#20]
你好，能问一下这个npm install 是安装的这个项目环境的包，还是安装了所有的。我是换了源安装的，感觉还是很慢，

**Comment by tikazyq** [comment]
`npm install`的时候可以加参数 `--registry=https://registry.npm.taobao.org`，这样会快一些

**Comment by AndrewAndrea** [comment]
恩，这个我已经换源了，就是感觉安装的包好多

**Comment by tikazyq** [comment]
建议可以用docker部署，这个更方便一些

**Comment by AndrewAndrea** [comment]
OK
