### ISSUE TITLE
文章发布到CSDN失败

### ISSUE THREAD

**Issue by detectiveHLH** [crawlab-team/artipub#26]
由于时间问题，暂时只提供CSDN的两个问题：

1. CSDN中，其实用户还没有登陆，但是却显示获取了cookies成功，应该是过期了。

导致puppeteer获取不到需要发发博客的按钮。然后导致错误。

2. 扫码登录了，解决了这个问题之后，虽然发布成功，但是Content丢失，只有工具默认的加的“本篇文章由一文多发平台 ArtiPub 自动发布”这一句话

**Comment by tikazyq** [comment]
感谢反馈，可以加微信 tikazyq1 了解详细情况

**Comment by tikazyq** [comment]
更换了编辑器之后，HTML内容没有保存到数据库，导致发布为空内容，已修复
