### ISSUE TITLE
无法发布到“今日头条”

### ISSUE THREAD

**Issue by lw2590** [crawlab-team/artipub#46]
今天使用v0.1.3版本，博文发布到“今日头条”时出现报错信息：Error: Evaluation failed: TypeError: Cannot read property 'getAttribute' of null at __puppeteer_evaluation_script__:2:62，麻烦处理一下，谢谢。

**Comment by huafeis** [comment]
我的cookie无法同步到头条

**Comment by tanliyuan** [comment]
已修复
