### ISSUE TITLE
10个平台发布结果反馈

### ISSUE THREAD

**Issue by guofuzhang** [crawlab-team/artipub#65]
1.掘金报错：Error: Evaluation failed: TypeError: Cannot read property 'click' of null at __puppeteer_evaluation_script__:2:78
2.简书报错：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputFooter (__puppeteer_evaluation_script__:4:8)
3.今日头条报错：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)
4.博客园报错：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)
5.V2ex报错：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)
6.微信公众号素材发布不成功，相关报错：RequestError: Error: form-data: ENOENT: no such file or directory, open '/Users/marvzhang/projects/artipub/public/favicon.png'

**Comment by tikazyq** [comment]
用最新的镜像么？

**Comment by tikazyq** [comment]
微信公众号可以忽略，还无法发布

**Comment by JeffreyBool** [comment]
> 用最新的镜像么？

最新下载的镜像也不行
