### ISSUE TITLE
CSDN发布报错

### ISSUE THREAD

**Issue by JeffreyBool** [crawlab-team/artipub#72]
Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)

**Comment by JinluZhang1126** [comment]
Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)
同样的错误，并且无法导入cookie登陆状态

**Comment by ThisIsRone** [comment]
![image](https://user-images.githubusercontent.com/45396945/85126882-eeba1b00-b260-11ea-9ae0-b369e467d4f2.png)
也是这个错误

**Comment by tanliyuan** [comment]
已修复
