### ISSUE TITLE
博客园发布失败

### ISSUE THREAD

**Issue by CharMingF** [crawlab-team/artipub#77]
![image](https://user-images.githubusercontent.com/7530342/69613495-9cb76b00-106c-11ea-9725-8d46bda41caf.png)
博客园发布失败了

**Comment by CharMingF** [comment]
其他CDSN\知乎\简书成功了

**Comment by JornTang** [comment]
跟你一样的问题，现在有解决怎么处理吗？

**Comment by szwgh** [comment]
同样的问题。刚刚下载的docker-compose安装的。

**Comment by DeppWang** [comment]
同样的问题

**Comment by keatonlao** [comment]
同问，无法发布文章到博客园，报错如下：

```
app_1    | [2020-04-13T23:17:42.736] [INFO] default - input editor title and content
app_1    | Error: Evaluation failed: TypeError: Cannot read property 'focus' of null
app_1    |     at inputTitle (__puppeteer_evaluation_script__:3:8)
```


## 环境

* Ubuntu  19.10
* Docker: 19.03.8
* Docker Compose: 1.25.5
* Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by JackKuang** [comment]
我也遇到类似问题了
SegmentFault：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)
CSDN：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)
博客园：Error: Evaluation failed: TypeError: Cannot read property 'focus' of null at inputTitle (__puppeteer_evaluation_script__:3:8)

**Comment by xugaoxiang** [comment]
这个报错好常见，好多个issue都提到了，请作者集中回复一下，或者在readme中写明。

**Comment by tanliyuan** [comment]
![image](https://user-images.githubusercontent.com/8876684/106988618-34553500-67ab-11eb-82f0-cdec055419ae.png)
![image](https://user-images.githubusercontent.com/8876684/106990387-1ab5ec80-67af-11eb-8007-9be2b05fea23.png)

博客园默认编辑器不是 markdown， 需要调整为markdown, 这样元素选择 ‘#md-editor' 才能正确
