### ISSUE TITLE
启动成功后，提示在3000端口，但打开什么也没有

### ISSUE THREAD

**Issue by freekingg** [crawlab-team/artipub#82]
artipub start 成功后

提示  listening on port 3000

但打开网址是get 404

**Comment by tikazyq** [comment]
用docker，不用npm包

**Comment by HoYor** [comment]
用docker，同404

**Comment by coolqingcheng** [comment]
同用npm包，打开localhost:3000
```
Cannot GET /
```
终端上显示的是**GET / 404 5.063 ms - 139**
无法显示出来。mongodb数据库已经初始化了基本的数据，两张表

**Comment by ncs19960831** [comment]
现在最新的前端似乎在8000

**Comment by tanliyuan** [comment]
前端是 8000， 后端是 3000，  localhost:3000访问返回“Cannot GET /” ，  是因为没有 “/” 这个请求 ， http://localhost:3000/platforms 可以用这个地址验证后端启动成功
