### ISSUE TITLE
发布文章报错

### ISSUE THREAD

**Issue by sunfujiancn** [crawlab-team/artipub#88]
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
app_1    |     at Promise.then (/app/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21)
app_1    |     at <anonymous>
app_1    |   -- ASYNC --
app_1    |     at Frame.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:111:15)
app_1    |     at Page.goto (/app/node_modules/puppeteer-core/lib/Page.js:674:49)
app_1    |     at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
app_1    |     at JianshuSpider.goToEditor (/app/spiders/base.js:200:21)
app_1    |     at JianshuSpider.run (/app/spiders/base.js:318:16)
app_1    |     at <anonymous>
app_1    |     at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }

**Comment by changtingQ** [comment]
me,too .Could you slove it ?

**Comment by tanliyuan** [comment]
已修复，有时网络慢，可以重试
